name: CI

on:
  workflow_dispatch:
    inputs:
      choice:
        type: choice
        description: Select the environment
        options:
        - dev
        - uat
        - prod
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: print environment
        run: | 
          echo "choice is ${{ github.event.inputs.choice }}" / ${{ inputs.choice }}

      - name: your action
        run: |
          echo "Now you can continue with your project!"
